.PHONY: init
init:
	cp $(PROJECT_DIR)/code/bin/GIZMO-SFF GIZMO
	cp $(PROJECT_DIR)/code/extern/grackle-gizmo-agora/input/CloudyData_UVB=HM2012.h5 .
	cp $(PROJECT_DIR)/code/extern/gizmo-agora/cooling/TREECOOL .
	cp $(PROJECT_DIR)/data/ic/isolated/low.dat ic.dat
