channels:
  - qobilidop
  - conda-forge
  - defaults
dependencies:
  # Compilers
  - gcc
  - openmpi
  # Applications
  - fftw2-mpi
  - fftw3-mpi
  - gsl
  - hdf5
  - libtool
  # Analysis Tools
  - matplotlib
  - pandas
  - python=3
  - yt
